version: "3.8"
services:
  mongo:
    image: geppettotest/mongo-local:april2020
    container_name: mongo-1747
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - hpnewcolumnsproject_1747-volume:/data/db
    ports:
      - "27018:27017"
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u root -p root --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  camunda:
    image: geppettodistribution/camunda-local:Jan2021
    container_name: camunda-1747
    ports:
      - "0000:8080"

  authproxy:
    build: ../../../application/services/default_services/authproxy
    image: authproxy-1747
    container_name: authproxy-1747
    ports:
      - "0000:8001"
    env_file: .env
    depends_on:
      - mongo
      - camunda

  securitymanager:
    build: ../../../application/services/default_services/securitymanager
    image: securitymanager-1747
    container_name: securitymanager-1747
    ports:
      - "8003:8003"
    env_file: .env
    depends_on:
      - mongo
      - camunda

  camundaservice:
    build: ../../../application/services/default_services/camunda
    image: camundaservice-1747
    container_name: camundasvc-1747
    ports:
      - "8002:8002"
    env_file: .env
    depends_on:
      - mongo
      - camunda
      - securitymanager

  apigateway:
    build: ../../../application/services/custom_services/apigateway
    image: apigateway-1747
    container_name: apigateway-1747
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - camunda
      - camundaservice
      - authproxy
      - securitymanager
      - student
      - department
      - college
      - place



  student: 
    build: ../../../application/services/custom_services/student
    image: student-1747
    container_name: student-1747
    ports: 
      - 8005:8005
    env_file: .env
    depends_on:
      - mongo

  department: 
    build: ../../../application/services/custom_services/department
    image: department-1747
    container_name: department-1747
    ports: 
      - 8006:8006
    env_file: .env
    depends_on:
      - mongo

  college: 
    build: ../../../application/services/custom_services/college
    image: college-1747
    container_name: college-1747
    ports: 
      - 8007:8007
    env_file: .env
    depends_on:
      - mongo

  place: 
    build: ../../../application/services/custom_services/place
    image: place-1747
    container_name: place-1747
    ports: 
      - 8008:8008
    env_file: .env
    depends_on:
      - mongo


volumes:
  hpnewcolumnsproject_1747-volume:
    driver: local
